# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mov-11',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/mov-11',
                'lib_path': 'mov_11'},
  'syms': {'mov_11.core': {'mov_11.core.foo': ('core.html#foo', 'mov_11/core.py')}}}